name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew (Linux/macOS)
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # ✅ Debug: Check generated JAR file
      - name: Debug: List build/libs contents
        run: ls -lah build/libs

      # ✅ Ensure JAR file exists before Docker build
      - name: Check JAR File Exists
        run: test -f build/libs/*SNAPSHOT*.jar || (echo "JAR file not found!" && exit 1)

      # ✅ Log in to Docker Hub using DOCKERHUB_USERNAME and DOCKERHUB_TOKEN
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # ✅ Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t learner183/github-action-projects:latest .
          docker push learner183/github-action-projects:latest
